# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  postgresql:
    auth:
      existingSecret: myapp-db-secret
      username: "appuser"
      database: "mydb"
      password: "nopass"
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: postgres-app-password
        replicationPasswordKey: postgres-password
  security:
    allowInsecureImages: true

replicaCount: 1

image:
  repository: poc-helm-node-pg
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  myvalue: "Hello from BASE environment with PostgreSQL + Secret + node22-alpine"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

# PostgreSQL configuration (Bitnami dependency)
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0
    pullPolicy: Always
  primary:
    persistence:
      enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false

frontend:
  image:
    repository: nginx
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1
  resources: {}
  service:
    type: ClusterIP
    port: 80
